### ISSUE TITLE
media pipe sample 

### ISSUE THREAD

**Issue by instant-high** [uelordi01/mediapipe_faceswap#2]
Hello and thank you for sharing your code.

I've just installed your media-pipe face-swap sample and changed the code to read and write videofile instead of using a webcam.

Why are the swapped faces "freckled" (see my uploaded result screenshot) with black spots?
Using webcam is the same problem.

How can this be solved?

![swap](https://user-images.githubusercontent.com/77229558/139542278-d9601c79-cce2-4d29-ae2e-96032e0cbe96.jpg)

**Comment by uelordi01** [comment]
Hi @instant-high : 
Both algorithms (dlib68, mediapipe) uses delaunay triangulation and warping to swap the faces. So, in few words this face-swap algorithm takes the triangles of the face input image and makes the warping in the target face. 

This freckled effect could happen for the following reasons: 

- The mediapipe face landmark detection can be noisy depending on the input video file, and then it is possible that this triangles precission decrease in the image. 

- Also, check the resolution of the input (the image to replace) and the output resolution (target face in the video) image, if there is an important difference between them, there are probably precission problems in the warping process in the triangulation.

**Comment by instant-high** [comment]
Thank you. I've seen it depends on the resolution.
Maybe I can fix it implementing a colour correction using gaussian blur,  I've used that in another project.
