### ISSUE TITLE
Black dots on warped faces

### ISSUE THREAD

**Issue by gavspav** [uelordi01/mediapipe_faceswap#3]
Hi, I'm experiencing the following issue - warped faces have black dots on them.
I am guessing this is because the warped triangles don't always perfectly line up and there are a few gaps?
I can see some artefacts in the media_pipe_sample example.
I have used the code to put webcam faces in movie clips and I get [this result](https://drive.google.com/file/d/1Lp9dIR_2LKtXkja1jq9fNPVgwVuebq82/view?usp=sharing):
I can think of a few workarounds but I can't quite imagine what is going wrong here.
Any idea?

**Comment by gavspav** [comment]
I just tried experimenting with the border modes of the warpaffine function:

`warped_triangle = cv2.warpAffine(cropped_triangle, M, (w, h),borderMode=cv2.BORDER_REPLICATE)`

Works pretty well for me.

**Comment by uelordi01** [comment]
Thanks for your issue and the tip, I ´ll update the code as soon as I can.
